import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./(home)/_components/Header/Header";
import Footer from "./(home)/_components/Footer/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
